FROM node:16.15-slim
RUN mkdir /opt/pattern-library
# this expects a volume to be mounted to /opt/pattern-library
WORKDIR /opt/pattern-library
COPY package-lock.json \
    package.json \
    ./

RUN npm install
