ARG image_tag=latest
FROM --platform=linux/amd64 elifesciences/pattern-library_assets-builder:${image_tag}

COPY .ci/ .ci/
COPY project_tests.sh smoke_tests.sh wdio.conf.js ./
COPY source/_patterns/00-atoms/errors/ source/_patterns/00-atoms/errors/
COPY test-selenium/ test-selenium/
COPY test/ test/

RUN mkdir -p test/build
