ARG selenium_image_suffix=
FROM selenium/standalone-firefox${selenium_image_suffix}:3.11.0-bismuth
USER root
RUN apt-get update && apt-get install --no-install-recommends -y \
    mplayer \
    linux-sound-base \
    && rm -rf /var/lib/apt/lists/*
USER seluser
