ARG image_tag=latest
FROM elifesciences/pattern-library_assets-builder:${image_tag} AS assets-builder

FROM tianon/true:latest
ENV PROJECT_FOLDER=/srv/pattern-library
WORKDIR ${PROJECT_FOLDER}

COPY --from=assets-builder /srv/pattern-library/source/ ${PROJECT_FOLDER}/source

ARG description=
LABEL description=${description}
