assets:
  css:
    - $ref: ../../00-atoms/components/date.yaml#/assets/css
  js: []
schema:
  $schema: http://json-schema.org/draft-04/schema#
  type: object
  properties:
    typeLink:
      type: string
      minLength: 1
    type:
      type: string
      minLength: 1
    date:
      type: object
      $ref: ../../00-atoms/components/date.yaml#/schema
  required:
    - type
    - date
