assets:
  css:
    - meta.css
  js: []
schema:
  $schema: http://json-schema.org/draft-04/schema#
  type: object
  properties:
    typeLink:
      type: string
      minLength: 1
    type:
      type: string
      minLength: 1
    date:
      type: object
      properties:
        forHuman:
          type: string
          minLength: 1
        forMachine:
          type: string
          minLength: 1
      required:
        - forHuman
        - forMachine
  required:
    - type
    - date
